import { Injectable, Logger } from '@nestjs/common'
import { RagService } from '../rag/rag.service'
import { LlmService } from '../llm/llm.service'
import { detectLanguage } from '../common/utils/lang-detect.util'
import { AGENT_PROMPT_TEMPLATES } from '../common/prompts/chatbot.prompts'
import { MemoryService } from '../memory/memory.service'
import { AskDto } from './dto/ask.dto'

/**
 * AgentService
 *
 * Main orchestrator for chatbot interactions.  Handles message flow,
 * language detection, context retrieval (RAG), prompt building, LLM
 * interaction, and session memory management.
 */
@Injectable()
export class AgentService {
  private readonly logger = new Logger(AgentService.name)

  constructor(
    private readonly ragService: RagService,
    private readonly llmService: LlmService,
    private readonly memoryService: MemoryService,
  ) {}

  /**
   * Handles a new user chat input.
   *
   * 1. Detects input language (if not provided)
   * 2. Retrieves chat history and external context (RAG)
   * 3. Builds the LLM prompt using language‑appropriate templates
   * 4. Calls the LLM provider and saves both user input and agent reply
   *
   * @param options Chat options including user input, session ID and optional language.
   * @returns The agent's reply as generated by the LLM.
   */
  async chat(options: AskDto): Promise<string> {
    const { userInput, sessionId } = options
    let userLang = options.userLang
    this.logger.debug(`Received user input: "${userInput}" [sessionId: ${sessionId}]`)
    // Detect language of user input if not provided
    if (!userLang) {
      userLang = detectLanguage(userInput)
      this.logger.log(`Detected user language: ${userLang}`)
    } else {
      this.logger.log(`Using provided user language: ${userLang}`)
    }
    try {
      // Retrieve prior chat history for session
      const history = await this.memoryService.getHistory(sessionId)
      this.logger.debug(`Retrieved history for session: ${JSON.stringify(history)}`)
      // Retrieve additional context (e.g., RAG)
      const contextArr = await this.ragService.retrieveContext(userInput)
      const context = contextArr.join('\n---\n')
      this.logger.debug(`Retrieved external context: ${JSON.stringify(contextArr)}`)
      // Compose the memory/history block for the prompt
      const historyContext = history.map((m) => `${m.role === 'user' ? 'user' : 'agent'}: ${m.content}`).join('\n')
      // Build prompt using language‑appropriate template
      const template = AGENT_PROMPT_TEMPLATES[userLang] || AGENT_PROMPT_TEMPLATES['en']
      const prompt = template(`${historyContext}\n${context}`, userInput)
      this.logger.verbose(`Final prompt built for LLM:\n${prompt}`)
      // Call LLM to get response
      const answer = await this.llmService.generate(prompt, { userLang })
      this.logger.debug(`LLM generated answer: "${answer}"`)
      // Save both user question and agent reply to memory
      await this.memoryService.addMessage(sessionId, 'user', userInput)
      await this.memoryService.addMessage(sessionId, 'assistant', answer)
      this.logger.log(`History updated for session: ${sessionId}`)
      return answer
    } catch (error) {
      this.logger.error(`❌ Error processing chat: ${(error as Error).message}`, (error as Error).stack)
      throw error
    }
  }
}
