import { Injectable, Logger } from '@nestjs/common'
import { LlmService } from '../llm/llm.service'
import { AskDto } from './dto/ask.dto'

/**
 * AgentService
 *
 * Main entry point for chatbot interactions. Delegates the heavy lifting
 * (prompting, tools, memory and RAG) to the LlmService.
 */
@Injectable()
export class AgentService {
  private readonly logger = new Logger(AgentService.name)

  constructor(private readonly llmService: LlmService) {}

  /**
   * Handles a new user chat input.
   *
   * 1. Delegates to LlmService with the session context
   * 2. LlmService handles prompt, memory, tools, and RAG
   *
   * @param options Chat options including user input, session ID and optional language.
   * @returns The agent's reply as generated by the LLM.
   */
  async chat(options: AskDto): Promise<string> {
    const { userInput, sessionId } = options
    const userLang = options.userLang
    this.logger.debug(`Received user input: "${userInput}" [sessionId: ${sessionId}]`)
    try {
      const answer = await this.llmService.generate(userInput, { sessionId, userLang })
      this.logger.debug(`LLM generated answer: "${answer}"`)
      return answer
    } catch (error) {
      this.logger.error(`❌ Error processing chat: ${(error as Error).message}`, (error as Error).stack)
      throw error
    }
  }
}
